#!/bin/sh
PREREQ="udev"
prereqs() { echo "$PREREQ"; }
case $1 in prereqs) prereqs; exit 0;; esac

# cryptdevice=/dev/vda2:crypt_root parametresini oku
CRYPT_PARAM=$(cat /proc/cmdline | tr ' ' '\n' | grep '^cryptdevice=' | sed 's/^cryptdevice=//')
LUKS_DEV=$(echo "$CRYPT_PARAM" | cut -d':' -f1)
MAPPER_NAME=$(echo "$CRYPT_PARAM" | cut -d':' -f2)

if [ -z "$LUKS_DEV" ]; then
    echo "No Luks device found."
fi

sleep 3

IS_LUKS=$(cryptsetup isLuks "$LUKS_DEV" 2>/dev/null && echo "true" || echo "false")

if [ "$IS_LUKS" != "true" ]; then
    echo "Encryption device $LUKS_DEV bulunamadi veya LUKS formatinda degil."
fi

# Sifre dogru girilene kadar donguye gir
while true; do
    # PASS=$(unl0kr --rotate=1 --message="Disk decrypt sifresini giriniz")
    PASS=$(unl0kr)

    if [ "$IS_LUKS" != "true" ]; then
        break
    fi

    if [ -n "$PASS" ]; then
        if echo "$PASS" | cryptsetup luksOpen "$LUKS_DEV" "$MAPPER_NAME"; then
            echo "Basarili: $LUKS_DEV acildi -> /dev/mapper/$MAPPER_NAME"
            break
        else
            echo "Hata: Sifre yanlis, tekrar deneyin."
            sleep 1
        fi
    fi
done
unset PASS
