# FireWire — DMA saldirilarina acik
install firewire-core /bin/false
install firewire-ohci /bin/false
install firewire-sbp2 /bin/false

# Thunderbolt — DMA saldirilarina acik
install thunderbolt /bin/false

# Kullanilmayan ag protokolleri — saldiri yuzeyi
install dccp /bin/false
install sctp /bin/false
install rds /bin/false
install tipc /bin/false
install n-hdlc /bin/false

# Kullanilmayan dosya sistemi suruculeri
install cramfs /bin/false
install freevxfs /bin/false
install jffs2 /bin/false
install hfs /bin/false
install hfsplus /bin/false
install udf /bin/false
