# T3 Foundation Gemstone Project [t3gemstone.org]
# SPDX-License-Identifier: Apache-2.0
# Do not abuse this file. Only tasks appealing to everyone should be added.

version: '3'

tasks:
  publish-debs:
    desc: Publish the latest DEB files to the package repository
    cmds:
      - utils/publish_debs.sh {{ .DEB_DIR }} {{ .REPO_NAME }} {{ .DISTRO }}
    requires:
        vars:
          - name: DEB_DIR
          - name: REPO_NAME
            enum: [ beagley-ai, intel-corei7-64, t3-gem-o1, gemstone ]
          - name: DISTRO
            enum:
              - bsp          # kernel, bootloader and firmware packages
              - jammy        # Ubuntu 22
              - noble        # Ubuntu 24
              - bullseye     # Debian 11
              - bookworm     # Debian 12
              - yirmiuc-deb  # Pardus 23
