#!/bin/sh
PREREQ=""
prereqs() { echo "$PREREQ"; }
case $1 in prereqs) prereqs; exit 0;; esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/bin/unl0kr /bin
copy_exec /usr/bin/cryptsetup /bin

copy_modules_dir kernel/drivers/input/touchscreen
copy_modules_dir kernel/drivers/video/fbdev
