PermitEmptyPasswords no
PasswordAuthentication yes

MaxAuthTries 3
MaxSessions 5

ClientAliveInterval 300
ClientAliveCountMax 2
LoginGraceTime 30

X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no

PermitUserEnvironment no
Compression no
TCPKeepAlive no

Ciphers aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com
KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256

# Match bloklari her zaman dosyanin sonunda olmali
Match User root
    PermitRootLogin yes
    AuthenticationMethods publickey,password
Match All
    PermitRootLogin no
